const languages = {
  en: "English",
  hi: "Hindi",
  ur: "Urdu",
  bn: "Bengali",
  ta: "Tamil",
  te: "Telugu",
  kn: "Kannada",
  ml: "Malayalam",
  mr: "Marathi",
  gu: "Gujarati",
  pa: "Punjabi",
  or: "Odia",
  as: "Assamese",
  sa: "Sanskrit",
  ne: "Nepali",
  ks: "Kashmiri",
  kok: "Konkani",
  mai: "Maithili",
  doi: "Dogri",
  mni: "Manipuri",
  brx: "Bodo",
  sat: "Santhali",

  fr: "French",
  de: "German",
  es: "Spanish",
  pt: "Portuguese",
  it: "Italian",
  ru: "Russian",

  ja: "Japanese",
  ko: "Korean",
  zh: "Chinese",
  th: "Thai",
  vi: "Vietnamese",
  id: "Indonesian",
  ms: "Malay",

  ar: "Arabic",
  fa: "Persian",
  tr: "Turkish",
  he: "Hebrew",

  nl: "Dutch",
  sv: "Swedish",
  no: "Norwegian",
  da: "Danish",
  fi: "Finnish",
  pl: "Polish",
  cs: "Czech",
  hu: "Hungarian",
  ro: "Romanian",
  bg: "Bulgarian",
  uk: "Ukrainian",
};

export default languages;


// const languages = {
//   "en-US": "English (United States)",
//   "en-GB": "English (United Kingdom)",
//   "hi-IN": "Hindi (India)",
//   "ur-IN": "Urdu (India)",
//   "bn-IN": "Bengali (India)",
//   "ta-IN": "Tamil (India)",
//   "te-IN": "Telugu (India)",
//   "kn-IN": "Kannada (India)",
//   "ml-IN": "Malayalam (India)",
//   "mr-IN": "Marathi (India)",
//   "gu-IN": "Gujarati (India)",
//   "pa-IN": "Punjabi (India)",
//   "or-IN": "Odia (India)",
//   "as-IN": "Assamese (India)",
//   "sa-IN": "Sanskrit (India)",
//   "ne-IN": "Nepali (India)",
//   "ks-IN": "Kashmiri (India)",
//   "kok-IN": "Konkani (India)",
//   "mai-IN": "Maithili (India)",
//   "doi-IN": "Dogri (India)",
//   "mni-IN": "Manipuri (India)",
//   "brx-IN": "Bodo (India)",
//   "sat-IN": "Santhali (India)",

//   "fr-FR": "French (France)",
//   "fr-CA": "French (Canada)",
//   "de-DE": "German (Germany)",
//   "es-ES": "Spanish (Spain)",
//   "es-MX": "Spanish (Mexico)",
//   "pt-PT": "Portuguese (Portugal)",
//   "pt-BR": "Portuguese (Brazil)",
//   "it-IT": "Italian (Italy)",
//   "ru-RU": "Russian (Russia)",

//   "ja-JP": "Japanese (Japan)",
//   "ko-KR": "Korean (South Korea)",
//   "zh-CN": "Chinese (Simplified)",
//   "zh-TW": "Chinese (Traditional)",
//   "th-TH": "Thai (Thailand)",
//   "vi-VN": "Vietnamese (Vietnam)",
//   "id-ID": "Indonesian (Indonesia)",
//   "ms-MY": "Malay (Malaysia)",

//   "ar-SA": "Arabic (Saudi Arabia)",
//   "ar-EG": "Arabic (Egypt)",
//   "ar-AE": "Arabic (UAE)",
//   "fa-IR": "Persian (Iran)",
//   "tr-TR": "Turkish (Turkey)",
//   "he-IL": "Hebrew (Israel)",

//   "nl-NL": "Dutch (Netherlands)",
//   "sv-SE": "Swedish (Sweden)",
//   "no-NO": "Norwegian (Norway)",
//   "da-DK": "Danish (Denmark)",
//   "fi-FI": "Finnish (Finland)",
//   "pl-PL": "Polish (Poland)",
//   "cs-CZ": "Czech (Czech Republic)",
//   "hu-HU": "Hungarian (Hungary)",
//   "ro-RO": "Romanian (Romania)",
//   "bg-BG": "Bulgarian (Bulgaria)",
//   "uk-UA": "Ukrainian (Ukraine)"
// };

// export default languages;
